use_frameworks!

target 'STSegmentPageView_Example' do
  pod 'STSegmentPageView', :path => '../'

  target 'STSegmentPageView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
